apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flipkart-wallet-service
  title: Flipkart Wallet Service
  description: Manages Flipkart Wallet transactions, balances, and refunds.
  tags:
    - wallet
    - transactions
    - payments
  links:
    - url: https://flipkart.com/wallet/docs
      title: Wallet Service Docs
      icon: book
    - url: https://github.com/flipkart/wallet-service
      title: GitHub Repository
      icon: github
    - url: https://flipkart.com/wallet/status
      title: Wallet Service Status
      icon: heartbeat
    - url: https://flipkart.com/wallet/logs
      title: Service Logs
      icon: file-text
spec:
  type: service
  lifecycle: production
  owner: payments-team
  system: flipkart-ecommerce-platform
  domain: flipkart-payments
  providesApis:
    - flipkart-wallet-api
