apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flipkart-order-service
  description: Manages order processing, tracking, and history for Flipkart customers.
  annotations:
    github.com/project-slug: flipkart/flipkart-order-service
    backstage.io/techdocs-ref: dir:.
    pagerduty.com/service-id: flipkart-order-pagerduty
    sonarcloud.io/project-key: flipkart/flipkart-order-service
    circleci.com/project-slug: github/flipkart/flipkart-order-service
    grafana/dashboard-url: https://grafana.flipkart.com/d/abc123/orders-dashboard
    backstage.io/kubernetes-id: flipkart-order-service
  tags:
    - ecommerce
    - microservice
    - orders
    - payments
  links:
    - url: https://www.google.com/
      title: API Documentation
      icon: book
    - title: Production Dashboard
      url: https://grafana.flipkart.com/d/abc123/orders-dashboard
      icon: dashboard
    - title: GitHub Repository
      url: https://github.com/flipkart/flipkart-order-service
      icon: github
    - title: CI/CD Pipeline
      url: https://circleci.com/project/github/flipkart/flipkart-order-service
      icon: build
    - title: PagerDuty Alerts
      url: https://flipkart.pagerduty.com/services/flipkart-order-pagerduty
      icon: alert
    - title: Sentry Logs
      url: https://sentry.flipkart.com/projects/flipkart-order-service
      icon: bug
spec:
  type: service
  owner: infrastructure
  lifecycle: production
  system: flipkart-ecommerce-platform
  providesApis:
    - flipkart-order-api
    - flipkart-tracking-api
  consumesApis:
    - flipkart-payment-api
    - flipkart-inventory-api
  dependsOn:
    - resource:flipkart-database
    - component:flipkart-payment-service
    - component:flipkart-inventory-service
    - component:flipkart-shipping-service
  subcomponentOf: flipkart-service

